name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install JS dependencies
      run: yarn install
      
    - name: Lint codebase
      run: yarn lint:quiet

    - name: Analyse codebase
      run: yarn analyse

    - name: Run tests
      run: yarn test:coverage
